apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: db
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 851725335686.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
