name: Build & Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push MySQL
        run: |
          docker build -t my-mysql -f Dockerfile_mysql .
          docker tag my-mysql:latest ${{ steps.login-ecr.outputs.registry }}/my-mysql:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/my-mysql:latest

      - name: Build, Tag & Push App
        run: |
          docker build -t my-app -f Dockerfile .
          docker tag my-app:latest ${{ steps.login-ecr.outputs.registry }}/my-app:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/my-app:latest

