name: Build & Push to ECR

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      MYSQL_REPO: mysql-repo
      APP_REPO: webapp-repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}   # must be "us-east-1" for your repos

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push MySQL
        run: |
          docker build -t mysql-img -f Dockerfile_mysql .
          docker tag mysql-img:latest $ECR_REGISTRY/$MYSQL_REPO:latest
          docker push $ECR_REGISTRY/$MYSQL_REPO:latest

      - name: Build, Tag & Push App
        run: |
          docker build -t app-img -f Dockerfile .
          docker tag app-img:latest $ECR_REGISTRY/$APP_REPO:latest
          docker push $ECR_REGISTRY/$APP_REPO:latest
